# Generated by Django 4.2.3 on 2023-08-13 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_account_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(help_text='Comment ID', primary_key=True, serialize=False)),
                ('context', models.TextField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_id', models.BigAutoField(help_text='Feed ID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField(max_length=2000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_feed', to='account.account')),
            ],
            options={
                'db_table': 'Feed',
            },
        ),
        migrations.CreateModel(
            name='Feed_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/posting/default_image.jpeg', null=True, upload_to='feed_images/')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='posting.feed')),
            ],
            options={
                'db_table': 'Feed_image',
            },
        ),
        migrations.CreateModel(
            name='Comment_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/posting/default_image.jpeg', null=True, upload_to='feed_images/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posting.comment')),
            ],
            options={
                'db_table': 'Comment_image',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_in_comment', to='posting.feed'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_comment', to='account.account'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.BigAutoField(help_text='Call ID', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('call_status', models.BooleanField(default=True)),
                ('call_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_call', to='account.account')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_in_call', to='posting.feed')),
            ],
            options={
                'db_table': 'Call',
            },
        ),
    ]
