# Generated by Django 4.2.4 on 2023-08-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment_image",
            name="image",
            field=models.ImageField(
                blank=True,
                default="posting/default_image.jpeg",
                null=True,
                upload_to="feed_images/",
            ),
        ),
        migrations.AlterField(
            model_name="feed_image",
            name="image",
            field=models.ImageField(
                blank=True,
                default="posting/default_image.png",
                null=True,
                upload_to="posting/",
            ),
        ),
    ]
