# Generated by Django 4.2.4 on 2023-08-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0002_alter_comment_image_image_alter_feed_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed_image",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/posting/default_image.png",
                null=True,
                upload_to="media/posting/",
            ),
        ),
    ]
