# Generated by Django 4.2.3 on 2023-08-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='feed',
        ),
        migrations.AddField(
            model_name='comment',
            name='feed_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment_feed_id', to='posting.feed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user_id', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='feed_user_id', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment_image',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_comment_id', to='posting.comment'),
        ),
        migrations.AlterField(
            model_name='feed_image',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_feed_id', to='posting.feed'),
        ),
    ]
