# Generated by Django 4.2.3 on 2023-08-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_table'),
        ('posting', '0002_remove_comment_feed_comment_feed_id_comment_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='feed_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed_in_comment', to='posting.feed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed_in_user', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_in_feed', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment_image',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posting.comment'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feed_image',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='posting.feed'),
        ),
    ]
