# Generated by Django 4.2.3 on 2023-08-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
    ]
